services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=painaidee_db
      - DB_USER=postgres
      - DB_PASSWORD=PaiNaiDee123!
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "
        pip install -r requirements.txt &&
        python init_db.py &&
        python run.py
      "

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=painaidee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PaiNaiDee123!
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: